# https://github.com/philhawksworth/demo-netlify-plugin-fetch-feed/blob/master/netlify.yml
[[build]]
  command = "echo 'hi'"
  publish = "dist"



# [[plugins]]
#  package = "netlify-plugin-axe"
#    [plugins.inputs]
#      site = "netlify-plugin-axe-demo.netlify.com" # your Netlify site url
#      # https://github.com/dequelabs/axe-cli#running-specific-rules
#      # axeFlags = "--rules color-contrast,html-has-lang"
#      axeFlags = "--tags wcag2a"


[plugins]
  package = "./localAxe"
    [plugins.inputs]
      site = "netlify-plugin-axe-demo.netlify.com" # your Netlify site url
      # https://github.com/dequelabs/axe-cli#running-specific-rules
      # axeFlags = "--rules color-contrast,html-has-lang"
      axeFlags = "--tags wcag2a"