# https://github.com/philhawksworth/demo-netlify-plugin-fetch-feed/blob/master/netlify.yml
build:
  command: "#"
  publish: dist
  NODE_ENV: 10.15.3

# Config file `plugins` defines plugins used by build.
plugins:
  - package: netlify-plugin-axe
    config:
      site: mycoolsite.netlify.com # your Netlify site url
      # https://github.com/dequelabs/axe-cli#running-specific-rules
      axeFlags: --rules color-contrast,html-has-lang